/*  Authorization  */

export const authTypes = {
    USER_LOAD : 'USER_LOAD',
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    REGISTER_FAIL : 'REGISTER_FAIL',
    AUTH_ERROR : 'AUTH_ERROR',
    LOGIN_FAIL : 'LOGIN_FAIL',
    LOGOUT : 'LOGOUT'
};


/*   Common info */

export const commonInfoTypes = {
    CHANGE_SELECTED_MENU: 'CHANGE_SELECTED_MENU',
    SET_ALERT: 'SET_ALERT',
    REMOVE_ALERT: 'REMOVE_ALERT'
};


/*   Employees page */

export const employeesPageTypes = {
    EMPLOYEES_GET : 'EMPLOYEES_GET',
    EMPLOYEES_GET_FAILURE : 'EMPLOYEES_GET_FAILURE',
    DEPARTMENTS_GET : 'DEPARTMENTS_GET',
    DEPARTMENTS_GET_FAILURE : 'EMPLOYEES_GE',
    DEPARTMENT_ORDER_GET : 'DEPARTMENT_ORDER_GET',
    DEPARTMENT_ORDER_GET_FAILURE : 'DEPARTMENT_ORDER_GET_FAILURE',
    ALL_EMPLOYEES_LIST_GET : 'ALL_EMPLOYEES_LIST_GET',
    ALL_EMPLOYEES_LIST_GET_FAILURE : 'ALL_EMPLOYEES_LIST_GET_FAILURE',
    ADD_EMPLOYEE: 'ADD_EMPLOYEE',
    ADD_EMPLOYEE_FAILURE: 'ADD_EMPLOYEE_FAILURE',
    ONLY_DEPARTMENT: 'ONLY_DEPARTMENT',
    ONLY_DEPARTMENT_FAILURE: 'ONLY_DEPARTMENT_FAILURE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    DELETE_EMPLOYEE_FAILURE: 'DELETE_EMPLOYEE_FAILURE',
    EMPLOYEE_LOAD: 'EMPLOYEE_LOAD'
    /*UPDATE_DEPARTMENTS: 'UPDATE_DEPARTMENTS',
    UPDATE_DEPARTMENTS_FAILURE: 'UPDATE_DEPARTMENTS_FAILURE'*/
};


/*   Expenditures page */


export const expendituresPageTypes = {
    EXPENDITURE_GET : 'EXPENDITURE_GET',
    EXPENDITURE_GET_FAILURE : 'EXPENDITURE_GET_FAILURE',
    EXPENDITURE_UPDATE: 'EXPENDITURE_UPDATE',
    EXPENDITURE_UPDATE_FAILURE: 'EXPENDITURE_UPDATE_FAILURE',
    EXPENDITURE_LOAD: 'EXPENDITURE_LOAD'
};

/*   Projects page */

export const projectsPageTypes = {
    PROJECTS_NEW_GET : 'PROJECTS_NEW_GET',
    PROJECTS_NEW_GET_FAILURE : 'PROJECTS_NEW_GET_FAILURE',
    PROJECTS_PROCESS_GET : 'PROJECTS_PROCESS_GET',
    PROJECTS_PROCESS_GET_FAILURE : 'PROJECTS_PROCESS_GET_FAILURE',
    PROJECTS_CLOSE_GET : 'PROJECTS_CLOSE_GET',
    PROJECTS_CLOSE_GET_FAILURE : 'PROJECTS_CLOSE_GET_FAILURE',
    PROJECT_LOAD: 'PROJECT_LOAD',
    CURRENT_PROJECT_GET : 'CURRENT_PROJECT_GET',
    CURRENT_PROJECT_GET_FAILURE : 'CURRENT_PROJECT_GET_FAILURE',
    PROJECT_UPDATE: 'PROJECT_UPDATE',
    PROJECT_UPDATE_FAILURE: 'PROJECT_UPDATE_FAILURE',
    PROJECT_CLOSE: 'PROJECT_CLOSE',
    PROJECT_CLOSE_FAILURE: 'PROJECT_CLOSE_FAILURE',
    REPORT_ADD: 'REPORT_ADD',
    REPORT_ADD_FAILURE: 'REPORT_ADD_FAILURE',
    PROJECT_START: 'PROJECT_START',
    PROJECT_START_FAILURE: 'PROJECT_START_FAILURE',
    CREATE_PROJECT: 'CREATE_PROJECT',
    CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE'
};


/*   Reports page */

export const reportsPageTypes = {
    ALL_REPORTS_GET : 'ALL_REPORTS_GET',
    ALL_REPORTS_GET_FAILURE : 'ALL_REPORTS_GET_FAILURE',
    REPORT_UPDATE: 'REPORT_UPDATE',
    REPORT_UPDATE_FAILURE : 'REPORT_UPDATE_FAILURE',
};


/*   Requests money page */

export const requestsMoneyPageTypes = {
    REQUESTS_MONEY_GET : 'REQUESTS_MONEY_GET',
    REQUESTS_MONEY_GET_FAILURE : 'REQUESTS_MONEY_GET_FAILURE',
    SET_ANSWER_REQUEST: 'SET_ANSWER_REQUEST',
    SET_ANSWER_REQUEST_FAILURE: 'SET_ANSWER_REQUEST_FAILURE',
    CREATE_REQUEST_MONEY: 'CREATE_REQUEST_MONEY',
    CREATE_REQUEST_MONEY_FAILURE: 'CREATE_REQUEST_MONEY_FAILURE'
};


/*   Transactions page */

export const transactionsPageTypes = {
    TRANSACTION_GET : 'TRANSACTION_GET',
    TRANSACTION_GET_FAILURE : 'TRANSACTION_GET_FAILURE',
    TRANSACTION_UPDATE: 'TRANSACTION_UPDATE',
    TRANSACTION_UPDATE_FAILURE: 'TRANSACTION_UPDATE_FAILURE',
    TRANSACTION_LOAD: 'TRANSACTION_LOAD'
};


/*   Header */

export const headerPageTypes = {
    PERSONAL_INFO_GET : 'PERSONAL_INFO_GET',
    PERSONAL_INFO_GET_FAILURE : 'PERSONAL_INFO_GET_FAILURE'
};